- hosts: cluster

  vars_files:
    - vars.yml

  roles:
    - role: security
      become: yes

    - role: access

    - role: mpi
      become: yes




- hosts: client

  vars_files:
    - vars.yml

  roles:
    - role: nfs-client
      become: yes




- hosts: servers

  vars_files:
    - vars.yml

  roles:
    - role: nfs-servers
      become: yes
