- name: Install mpi package
  apt:
    update_cache: yes
    name:
      - openmpi-bin
    state: present

- name: Copy hosts file
  ansible.builtin.copy:
    src: .hosts
    dest: /home/{{ user }}
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Add environment variable to enable hosts file
  ansible.builtin.lineinfile:
    path: /home/{{ user }}/.bashrc
    line: export OMPI_MCA_orte_default_hostfile=$HOME/.hosts

