- name: Copy cluster key
  ansible.builtin.copy:
    src: cluster.pem
    dest: /home/{{ user }}/.ssh
    mode: '400'

- name: Copy ssh config file
  ansible.builtin.template:
    src: config.j2
    dest: /home/{{ user }}/.ssh/config
