- name: Install nfs pakcages
  apt:
    update_cache: yes
    name:
      - nfs-kernel-server
    state: present

- name: Ensure cloud folder is present
  ansible.builtin.file:
    path: "/home/{{ remote_user }}/cloud"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    state: directory

- name: Export cloud folder to servers
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: /home/{{ remote_user }}/cloud     *(rw)
  notify:
    - Restart nfs-kernel-server
