- name: Install nfs packages
  apt:
    update_cache: yes
    name:
      - nfs-common
    state: present

- name: Ensure cloud folder is present
  ansible.builtin.file:
    path: "/home/{{ user }}/cloud"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: directory

- name: Add mount point on fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: 10.0.0.4:/home/{{ user }}/cloud    /home/{{ user }}/cloud     nfs
  notify:
    - Update mount points
